// Dependency-free bundle of explicit, import-free modules. Fail closed when
// module syntax changes rather than silently dropping an unrecognised import.
import { readFile, writeFile } from 'node:fs/promises';
import { Script } from 'node:vm';

const root = new URL('./', import.meta.url);
const defaults = JSON.parse(await readFile(new URL('../app/src/default-settings.json', root), 'utf8'));
const { version } = JSON.parse(await readFile(new URL('package.json', root), 'utf8'));
const { width, height, tile, margin, seed, invert, autoIntro = true } = defaults;
const metadata = `// ==UserScript==
// @name         VeilCast Bilibili Restorer
// @namespace    veilcast.local
// @version      ${version}
// @description  使用与桌面端一致的 seed、tile、margin 在播放器上叠加还原画面
// @match        https://www.bilibili.com/video/*
// @run-at       document-idle
// @noframes
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_registerMenuCommand
// @grant        GM_unregisterMenuCommand
// ==/UserScript==
`;
const modules = [];
// jsQR ships as a UMD bundle; a local CommonJS shim keeps it off the page's window.
const jsqr = (await readFile(new URL('../viewer/vendor/jsQR.js', root), 'utf8')).replaceAll('\r\n', '\n');
modules.push(`// Source: ../viewer/vendor/jsQR.js (Apache-2.0, see viewer/vendor/jsQR.LICENSE)
const jsQR = (() => {
  const module = { exports: {} };
  const exports = module.exports;
  ${jsqr}
  return module.exports;
})();
const decodeQr = (image) => jsQR(image.data, image.width, image.height)?.data ?? null;`);
for (const path of ['../viewer/veilcast.js', 'src/settings.js', 'src/main.js']) {
  const source = (await readFile(new URL(path, root), 'utf8'))
    .replaceAll('\r\n', '\n')
    .replace(/^export (?=(?:function|const) )/gm, '');
  if (/^\s*(?:import|export)\s/m.test(source)) throw new Error(`Unsupported module syntax in ${path}`);
  modules.push(`// Source: ${path}\n${source}`);
}
const output = `${metadata}\n// Generated by userscript/build.mjs; edit source files, then rebuild.\n(() => {\n'use strict';\n${modules.join('\n')}\ninstallUserscript({
  createRestorer, scanIntro, decodeQr, validateSettings, querySettings, descriptionSettings, videoPageKey,
  pageSettings, rememberPageSettings, forgetPageSettings,
  defaults: ${JSON.stringify({ width, height, tile, margin, seed, invert, autoIntro })},
  storage: { get: GM_getValue, set: GM_setValue },
  menu: { register: GM_registerMenuCommand, unregister: GM_unregisterMenuCommand },
});\n})();\n`;
new Script(output, { filename: 'veilcast.user.js' });
const target = new URL('veilcast.user.js', root);
if (process.argv.includes('--check')) {
  const existing = (await readFile(target, 'utf8')).replaceAll('\r\n', '\n');
  if (existing !== output) throw new Error('Bundle is stale. Run node userscript/build.mjs');
  console.log('Userscript bundle matches sources and Tauri defaults.');
} else {
  await writeFile(target, output);
  console.log(`Built ${target.pathname} (${Buffer.byteLength(output)} bytes)`);
}
